name: gitlab推送

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@main
      
    - name: time GMT+8 北京时间
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai' 
     
    - name: Clone source code 克隆源码
      run: |
        git clone https://github.com/wudongdefeng/rss.io.git rss.io    
         
        git clone https://gitlab.com/wudongdefeng/rss-io.git ~/gitlab
   
    

    - name: copy some list files 复制文件
      run: |
        echo "https://wudongdefeng:${{ secrets.gitlab }}@gitlab.com">~/.git-credentials
        cp ./rss.io/docs/index.html ~/gitlab//index.html
    - name: Commit files 提交文件
      run: |
        cd ~/gitlab
        git config --global credential.helper store
        git config --local user.email "${{ secrets.youxiang }}"
        git config --local user.name "wudongdefeng"
        git add .
        git commit -m "空投已送达" -a
        git push -u origin master
